# Generated by Django 5.0.2 on 2024-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurta',
            old_name='fest',
            new_name='Occasion',
        ),
        migrations.AddField(
            model_name='kurta',
            name='design',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kurta',
            name='fabric',
            field=models.CharField(default='', max_length=50),
        ),
    ]
