# Generated by Django 5.0.2 on 2024-03-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_color_design_fabric_alter_kurta_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurta',
            name='image',
        ),
        migrations.AddField(
            model_name='kurta',
            name='back',
            field=models.ImageField(null=True, upload_to='kurta_images/'),
        ),
        migrations.AddField(
            model_name='kurta',
            name='main_image',
            field=models.ImageField(null=True, upload_to='kurta_images/'),
        ),
        migrations.AddField(
            model_name='kurta',
            name='zoom',
            field=models.ImageField(null=True, upload_to='kurta_images/'),
        ),
    ]
