# Generated by Django 5.0.2 on 2024-03-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_fest_kurta_occasion_kurta_design_kurta_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurta',
            name='design',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kurta',
            name='fabric',
            field=models.CharField(max_length=50),
        ),
    ]
