# Generated by Django 5.0.2 on 2024-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_kurta_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurta',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
