# Generated by Django 5.0.2 on 2024-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_date',
            field=models.DateField(null=True),
        ),
    ]
