# Generated by Django 5.0.2 on 2024-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_orders_shipping_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='raz_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='raz_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='raz_payment_sign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
